<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\External\ExternalKeyhCommon.props" Condition="'$(_ExternalKeyhCommonPropsImported)' != 'true'" />
  <PropertyGroup>
    <PublicIncludeDirectories>$(MSBuildThisFileDirectory);$(PublicIncludeDirectories)</PublicIncludeDirectories>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>$(PublicPreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ForcedIncludeFiles>%(ForcedIncludeFiles);NetworkSystemPch.h;</ForcedIncludeFiles>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(KeyhCommonOutputDir);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>$(KeyhCommonReflectSystemLibrary);$(KeyhCommonCommonBaseLibrary);%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
