<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VcpkgEnabled Condition="'$(VcpkgEnabled)' == ''">true</VcpkgEnabled>
    <VcpkgEnableManifest Condition="'$(VcpkgEnableManifest)' == ''">true</VcpkgEnableManifest>
    <VcpkgManifestInstall Condition="'$(VcpkgManifestInstall)' == ''">true</VcpkgManifestInstall>
    <VcpkgManifestRoot Condition="'$(VcpkgManifestRoot)' == ''">$(MSBuildThisFileDirectory)External\</VcpkgManifestRoot>
    <VcpkgManifestRoot>$([MSBuild]::EnsureTrailingSlash('$(VcpkgManifestRoot)'))</VcpkgManifestRoot>
    <VcpkgTriplet Condition="'$(VcpkgTriplet)' == '' and '$(Platform)' == 'x64'">x64-windows</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(VcpkgTriplet)' == '' and ('$(Platform)' == 'Win32' or '$(Platform)' == 'x86')">x86-windows</VcpkgTriplet>
    <VcpkgInstalledDir Condition="'$(VcpkgInstalledDir)' == ''">$(VcpkgManifestRoot)vcpkg_installed\$(VcpkgTriplet)\</VcpkgInstalledDir>
    <VcpkgInstalledDir>$([MSBuild]::EnsureTrailingSlash('$(VcpkgInstalledDir)'))</VcpkgInstalledDir>
    <VcpkgAutoLink Condition="'$(VcpkgAutoLink)' == ''">false</VcpkgAutoLink>
  </PropertyGroup>
</Project>
